import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Alert, ActivityIndicator, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../context/ThemeContext';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export default function ExportScreen() {
  const router = useRouter();
  const { colors, isDark } = useTheme();
  const params = useLocalSearchParams();
  const [loading, setLoading] = useState(false);

  let result = null;
  try {
    if (params.resultData) {
      result = JSON.parse(params.resultData as string);
    }
  } catch (e) {
    console.error("Failed to parse result data");
  }

  const generateHTML = () => {
    if (!result) return '<h1>No Data Available</h1>';

    const risks = result.risks || [];
    const clauses = result.clauses || [];
    const summaries = result.summaries || [];

    return `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1E293B; background: #fff; }
            .header { border-bottom: 2px solid #1A365D; padding-bottom: 20px; margin-bottom: 30px; }
            h1 { color: #1A365D; margin: 0; }
            .score-box { background: #F1F5F9; padding: 20px; border-radius: 12px; margin-bottom: 30px; display: flex; align-items: center; }
            .score { font-size: 48px; color: #EF4444; font-weight: bold; margin-right: 20px; }
            .level { font-size: 20px; font-weight: bold; color: #475569; text-transform: uppercase; }
            .section { margin-top: 30px; }
            .section-title { font-size: 20px; font-weight: bold; color: #1A365D; margin-bottom: 15px; border-left: 4px solid #1A365D; padding-left: 12px; }
            .card { background: #fff; padding: 16px; border-radius: 12px; margin-bottom: 12px; border: 1px solid #E2E8F0; }
            .risk-title { font-weight: bold; color: #1E293B; font-size: 16px; }
            .risk-desc { color: #64748B; font-size: 14px; margin-top: 6px; line-height: 1.5; }
            .bullet { margin-bottom: 10px; line-height: 1.6; }
            .clause-tag { display: inline-block; background: #E2E8F0; padding: 6px 12px; borderRadius: 8px; margin: 4px; font-size: 12px; fontWeight: bold; color: #1A365D; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>LegalRisk Analysis Report</h1>
            <p style="color: #64748B; margin-top: 5px;">Document: ${result.filename || 'Untitled Document'}</p>
          </div>

          <div class="score-box">
            <span class="score">${result.risk_score}/100</span>
            <span class="level">${result.risk_level}</span>
          </div>
          
          <div class="section">
            <div class="section-title">Document Overview</div>
            <div class="card">
              ${summaries.map((s: string) => `<div class="bullet">• ${s}</div>`).join('')}
            </div>
          </div>

          <div class="section">
            <div class="section-title">Critical Concerns</div>
            ${risks.map((r: any) => `
              <div class="card" style="border-left: 5px solid #EF4444;">
                <div class="risk-title">${r.type || 'Potential Risk'}</div>
                <div class="risk-desc">${r.description}</div>
              </div>
            `).join('')}
          </div>

          <div class="section">
            <div class="section-title">Detected Clauses</div>
            <div style="padding: 10px;">
              ${clauses.map((c: string) => `<span class="clause-tag">${c}</span>`).join('')}
            </div>
          </div>
          
          <div style="margin-top: 60px; padding-top: 20px; border-top: 1px solid #E2E8F0; color: #94A3B8; font-size: 12px; text-align: center;">
            Generated by Legal Auditor AI on ${new Date().toLocaleDateString()}
            <br>CONFIDENTIAL REPORT
          </div>
        </body>
      </html>
    `;
  };


  const handlePrint = async () => {
    setLoading(true);
    try {
      const html = generateHTML();
      if (Platform.OS === 'web') {
        // On web, open a new window with the HTML and trigger print to ensure we print the report, not the app UI
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(html);
          printWindow.document.close();
          // Give it a moment to load styles before printing
          setTimeout(() => {
            printWindow.focus();
            printWindow.print();
          }, 250);
        } else {
          Alert.alert("Error", "Pop-up blocked. Please allow pop-ups to print the report.");
        }
      } else {
        await Print.printAsync({ html });
      }
    } catch (e: any) {
      Alert.alert("Error", e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    setLoading(true);
    try {
      const html = generateHTML();
      if (Platform.OS === 'web') {
        // Dynamically load html2pdf to generate a real PDF blob on the client
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
        script.onload = () => {
          const opt = {
            margin: 0.5,
            filename: 'LegalRisk_Report.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
          };

          // @ts-ignore
          window.html2pdf().set(opt).from(html).output('blob').then(async (pdfBlob: Blob) => {
            const file = new File([pdfBlob], 'LegalRisk_Report.pdf', { type: 'application/pdf' });

            if (navigator.canShare && navigator.canShare({ files: [file] })) {
              try {
                await navigator.share({
                  files: [file],
                  title: 'LegalRisk Report',
                  text: 'Here is the Legal Risk Analysis Report.'
                });
              } catch (err) {
                console.log("User cancelled share");
              }
            } else {
              // Fallback if browser (like Desktop Chrome) doesn't support sharing files
              const url = URL.createObjectURL(pdfBlob);
              const a = document.createElement('a');
              a.href = url;
              a.download = 'LegalRisk_Report.pdf';
              a.click();
              Alert.alert("Share via Attachment", "Your browser doesn't support direct PDF sharing. The PDF has been downloaded so you can easily attach it to WhatsApp or Email.");
            }
            setLoading(false);
          });
        };
        document.body.appendChild(script);
        return; // wait for script to finish
      } else {
        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Share Risk Report',
          UTI: 'com.adobe.pdf'
        });
      }
    } catch (e: any) {
      Alert.alert("Error", e.message);
      setLoading(false);
    }
  };

  const Option = ({ icon, title, desc, onPress }: any) => (
    <TouchableOpacity style={[styles.option, { backgroundColor: colors.card, borderColor: colors.divider }]} onPress={onPress}>
      <View style={[styles.iconBox, { backgroundColor: colors.primary + '15' }]}>
        <Ionicons name={icon} size={24} color={colors.primary} />
      </View>
      <View style={styles.optionInfo}>
        <Text style={[styles.optionTitle, { color: colors.text }]}>{title}</Text>
        <Text style={[styles.optionDesc, { color: colors.textSecondary }]}>{desc}</Text>
      </View>
      <Ionicons name="chevron-forward" size={20} color={colors.textSecondary} />
    </TouchableOpacity>
  );

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: colors.bg }]}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Ionicons name="close" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.text }]}>Export Report</Text>
        <View style={{ width: 24 }} />
      </View>

      <ScrollView contentContainerStyle={styles.container}>
        <View style={[styles.previewCard, { backgroundColor: colors.card, borderColor: colors.divider }]}>
          <Ionicons name="document-text" size={64} color={colors.primary} />
          <Text style={[styles.previewTitle, { color: colors.text }]}>Risk_Analysis_Report.pdf</Text>
          <Text style={[styles.previewMeta, { color: colors.textSecondary }]}>Generated today • 1.2 MB</Text>
        </View>

        <Text style={[styles.sectionTitle, { color: colors.textSecondary }]}>Export & Share</Text>

        <Option
          icon="share-social-outline"
          title="Share PDF Report"
          desc="Send via WhatsApp, Email, or Slack"
          onPress={handleShare}
        />

        <Option
          icon="print-outline"
          title="Print or Save"
          desc="Generate PDF and print locally"
          onPress={handlePrint}
        />

        {loading && <ActivityIndicator size="large" color={colors.primary} style={{ marginTop: 20 }} />}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 24 },
  headerTitle: { fontSize: 22, fontWeight: '800' },
  container: { padding: 24 },
  previewCard: { alignItems: 'center', padding: 40, borderRadius: 24, marginBottom: 32, borderWidth: 1 },
  previewTitle: { fontSize: 20, fontWeight: '800', marginTop: 20 },
  previewMeta: { fontSize: 14, marginTop: 6 },
  sectionTitle: { fontSize: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 16, marginLeft: 4 },
  option: { flexDirection: 'row', alignItems: 'center', padding: 20, borderRadius: 20, marginBottom: 12, borderWidth: 1 },
  iconBox: { width: 52, height: 52, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  optionInfo: { flex: 1 },
  optionTitle: { fontSize: 17, fontWeight: '700' },
  optionDesc: { fontSize: 13, marginTop: 4 },
  mainBtn: { height: 64, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginTop: 20 },
  mainBtnText: { color: '#fff', fontSize: 18, fontWeight: '700' }
});
